import PropTypes from 'prop-types'
import { Box, Typography, Paper, IconButton, Divider } from '@mui/material'
import { IconX, IconMail } from '@tabler/icons-react'

const EmailPreviewPanel = ({ summary, answers, onClose }) => {
    const topic = answers?.topic || answers?.goal || 'your topic'
    const sources = Array.isArray(answers?.sources) ? answers.sources.join(', ') : answers?.sources || 'Web'
    const delivery = answers?.delivery || 'Email'
    
    // Generate preview content
    const subject = `Daily AI News: ${topic}`
    const previewBody = `
Hello!

Here's your research summary for "${topic}".

📊 Sources: ${sources}
🔍 What I found:

• [Research results will appear here after the workflow runs]
• AI-powered analysis and synthesis
• Key insights and trends
• Relevant links and citations

This is an automated report generated by your Flowise research workflow.

---
Powered by Flowise AI
    `.trim()

    return (
        <Box sx={{ 
            position: 'relative',
            border: '1px solid #e0e0e0', 
            borderRadius: 2, 
            p: 2, 
            my: 2,
            backgroundColor: '#fafafa'
        }}>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <IconMail size={20} color="#2196F3" />
                    <Typography variant="subtitle2" color="primary">
                        Email Preview
                    </Typography>
                </Box>
                <IconButton size="small" onClick={onClose}>
                    <IconX size={18} />
                </IconButton>
            </Box>

            <Paper elevation={0} sx={{ border: '1px solid #e0e0e0', borderRadius: 1 }}>
                <Box sx={{ p: 2, backgroundColor: '#fff' }}>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 0.5 }}>
                        Subject:
                    </Typography>
                    <Typography variant="body2" sx={{ fontWeight: 600, mb: 2 }}>
                        {subject}
                    </Typography>
                    
                    <Divider sx={{ my: 1.5 }} />
                    
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1 }}>
                        Message:
                    </Typography>
                    <Typography 
                        variant="body2" 
                        sx={{ 
                            whiteSpace: 'pre-wrap', 
                            fontFamily: 'monospace',
                            fontSize: '0.85rem',
                            color: 'text.secondary',
                            lineHeight: 1.6
                        }}
                    >
                        {previewBody}
                    </Typography>
                </Box>
            </Paper>

            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1.5, fontStyle: 'italic' }}>
                💡 This is a preview. Actual content will be generated when the workflow runs.
            </Typography>
        </Box>
    )
}

EmailPreviewPanel.propTypes = {
    summary: PropTypes.string,
    answers: PropTypes.object,
    onClose: PropTypes.func.isRequired
}

export default EmailPreviewPanel

